# Generated by Django 4.2.15 on 2024-08-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
