# Generated by Django 4.2.15 on 2024-08-15 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Technology', 'Technology'), ('Gadgets', 'Gadgets'), ('Software', 'Software'), ('AI', 'AI'), ('Startups', 'Startups'), ('Health', 'Health'), ('Fitness', 'Fitness'), ('Travel', 'Travel'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Entertainment', 'Entertainment'), ('Movies', 'Movies'), ('Music', 'Music'), ('Sports', 'Sports'), ('Finance', 'Finance'), ('Economy', 'Economy'), ('Business', 'Business'), ('Science', 'Science'), ('Space', 'Space'), ('Physics', 'Physics'), ('Biology', 'Biology'), ('Environment', 'Environment'), ('Art', 'Art'), ('History', 'History'), ('Philosophy', 'Philosophy'), ('Education', 'Education'), ('Career', 'Career'), ('Politics', 'Politics'), ('Opinion', 'Opinion'), ('Automotive', 'Automotive'), ('Home', 'Home'), ('Parenting', 'Parenting'), ('Gaming', 'Gaming'), ('Religion', 'Religion')], max_length=100, unique=True)),
            ],
        ),
    ]
