# Generated by Django 4.2.15 on 2024-08-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.tag'),
        ),
    ]
