# Generated by Django 4.2.15 on 2024-08-15 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_blogpage_category_remove_blogpage_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='allow_comments',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='view_count',
        ),
    ]
