# Generated by Django 4.2.15 on 2024-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_blogpage_allow_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='featured_image',
            new_name='profile_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='id',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='slug',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='status',
            field=models.CharField(choices=[('draft', 'Pending'), ('published', 'Published')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='title',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
