# Generated by Django 4.2.15 on 2024-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
