# Generated by Django 4.2.15 on 2024-09-02 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_article_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_image',
            field=models.ImageField(upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='page_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='main.blogpage'),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='profile_image',
            field=models.ImageField(default=0, upload_to='blog_images/'),
            preserve_default=False,
        ),
    ]
