# Generated by Django 5.1 on 2024-09-03 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_article_article_image_alter_article_page_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
