# Generated by Django 3.2.8 on 2025-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_article_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
    ]
